apiVersion: v1
kind: ConfigMap
metadata:
  name: cms-config
  namespace: dev-cms
  labels:
    app.kubernetes.io/name: cms
    app.kubernetes.io/app: cms
    app.kubernetes.io/version: "1"
    app.kubernetes.io/component: full-stack
data:
  NODE_ENV: "dev"
  CMS_PORT: "3827"
  