replicaCount: 1

namespace: "dev-cms"

image:
  repository: 36****4891.dkr.ecr.ap-northeast-2.amazonaws.com/ecr-dev-cms
  pullPolicy: IfNotPresent
  tag: "latest"


envData:
  CRON : "ENABLE"
  NODE_ENV: "dev"
  CMS_PORT: "3827"
