apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cms-cron.fullname" . }}-config
  namespace: {{ .Values.namespace }}
  labels:
    {{ include "cms-cron.labels" . | nindent 4 }}
data:
  config.json: |
{{ .Values.configJson | indent 4 }}
