apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cms-cron.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "cms-cron.labels" . | nindent 4 }}
    app.kubernetes.io/component: cron
spec:
  replicas: {{ .Values.replicaCount }} # 팟 몇개를 생성할건지
  strategy: # 애플리케이션을 배포(업데이트)할 때 어떤 방식으로 Pod를 교체할지 정의
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ .Values.maxSurge }} # 새 팟 생성
      maxUnavailable: {{ .Values.maxUnavailable }} # 생성되면 교체로 꺼질 팟 수
  selector: # 이 Deployment가 관리할 Pod를 선택하는 기준
    matchLabels:
      app: {{ include "cms-cron.name" . }}
  template: # 실제 생성될 Pod의 템플릿 정의
    metadata: # pod의 라벨링 service 가 Pod 라벨로 찾아감
      labels:
        app: {{ include "cms-cron.name" . }}
    spec:
      containers: # 팟 내부  컨테이너 설정
        - name: {{ include "cms-cron.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }} 
          envFrom: # ConfigMap의 모든 key-value를 환경변수로 주입
            - configMapRef:
                name: {{ include "cms-cron.fullname" . }}-config
          {{- with .Values.resources }}
          resources:   # (CPU/메모리 요청 및 제한)
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.startupProbe }} 
          startupProbe: # 처음 뜰 때까지 보호
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:  # 체크안되면 로드밸런서(ClusterIP, Service)트래픽안보냄.
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.livenessProbe }}
          livenessProbe: #앱의 헬스체크 . 헬싱안될시 pod안의 컨테이너 kill 하고 재시작 (컨테이너자가복구)
            {{- toYaml . | nindent 12 }}
          {{- end }}