replicaCount: 2

namespace: "prod-cms"

image:
  repository: 36548****1.dkr.ecr.ap-northeast-2.amazonaws.com/ecr-dev-cms
  pullPolicy: IfNotPresent
  tag: "latest"

autoscaling:
  enabled: true
  minReplicas: 4
  maxReplicas: 10

envData:
  NODE_ENV: "prod"
  CMS_PORT: "3827"
