replicaCount: 2

namespace: "dev-cms"

image:
  pullPolicy: IfNotPresent
  tag: "0.0.2"

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10


envData:
  NODE_ENV: "dev"
  TMP_TEST: "GOOD"
