replicaCount: 2

namespace: "dev-cms"

image:
  pullPolicy: IfNotPresent
  tag: "latest"

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10


envData:
  NODE_ENV: "dev"
  CMS_PORT: "3827"
