apiVersion: v1
kind: ConfigMap
metadata:
  name: cms-cron-config
  namespace: dev-cms
  labels:
    app.kubernetes.io/name: cms-cron
    app.kubernetes.io/app: cms-cron
    app.kubernetes.io/version: "1"
    app.kubernetes.io/component: cron
data:
  NODE_ENV: "dev"
  CMS_PORT: "3827"
  